// 标准资料：区域清单与初始模板/巡检/复核种子数据（纯数据，不含判定逻辑）
import type { InspectionRecord, InspectionTemplate, PersistedState, ReviewTask } from "./types";

export const AREAS = ["加油区", "油罐区", "收银区"] as const;

export const INSPECTORS = ["何鑫", "张倩", "王主任", "李工", "赵敏"] as const;

const seedTemplates: InspectionTemplate[] = [
  {
    id: "tpl-fuel-v1",
    name: "加油区日常巡检标准",
    area: "加油区",
    version: 1,
    status: "published",
    window: { start: "2026-09-01", end: "2026-09-30" },
    publishedAt: "2026-08-31T09:00:00.000Z",
    createdAt: "2026-08-30T09:00:00.000Z",
    items: [
      {
        id: "item-fuel-pressure",
        name: "加油机出口压力",
        device: "1号加油机",
        type: "number",
        unit: "MPa",
        min: 0.15,
        max: 0.3,
        required: true,
      },
      {
        id: "item-fuel-vapor",
        name: "油气回收真空度",
        device: "油气回收泵",
        type: "number",
        unit: "kPa",
        min: -6,
        max: -2,
        required: true,
      },
      {
        id: "item-fuel-hose",
        name: "加油枪软管外观",
        device: "2号加油机",
        type: "select",
        options: ["完好", "破损"],
        required: true,
      },
    ],
  },
  {
    id: "tpl-tank-v1",
    name: "油罐区安全巡检标准",
    area: "油罐区",
    version: 1,
    status: "published",
    window: { start: "2026-09-01", end: "2026-09-30" },
    publishedAt: "2026-08-31T09:00:00.000Z",
    createdAt: "2026-08-30T09:10:00.000Z",
    items: [
      {
        id: "item-tank-level",
        name: "油罐液位",
        device: "2号柴油罐",
        type: "number",
        unit: "mm",
        min: 800,
        max: 2400,
        required: true,
      },
      {
        id: "item-tank-gas",
        name: "可燃气浓度",
        device: "罐区气体报警器",
        type: "number",
        unit: "%LEL",
        min: 0,
        max: 10,
        required: true,
      },
      {
        id: "item-tank-seal",
        name: "卸油口密封",
        device: "卸油口",
        type: "select",
        options: ["完好", "老化", "渗漏"],
        required: true,
      },
    ],
  },
  {
    id: "tpl-cashier-draft",
    name: "收银区安防巡检标准",
    area: "收银区",
    version: 1,
    status: "draft",
    window: { start: "2026-10-01", end: "2026-10-31" },
    createdAt: "2026-09-20T02:00:00.000Z",
    items: [
      {
        id: "item-cashier-camera",
        name: "监控摄像头在线",
        device: "收银台摄像头",
        type: "select",
        options: ["在线", "离线"],
        required: true,
      },
    ],
  },
];

const seedRecords: InspectionRecord[] = [
  {
    id: "rec-fuel-0922",
    area: "加油区",
    inspector: "何鑫",
    inspectedAt: "2026-09-22T09:30",
    submittedAt: "2026-09-22T01:40:00.000Z",
    templateId: "tpl-fuel-v1",
    templateName: "加油区日常巡检标准",
    templateVersion: 1,
    entries: [
      {
        id: "entry-fuel-pressure-0922",
        itemId: "item-fuel-pressure",
        name: "加油机出口压力",
        device: "1号加油机",
        required: true,
        frozen: { type: "number", unit: "MPa", min: 0.15, max: 0.3 },
        value: "0.22",
        judgement: "normal",
        closure: { status: "open" },
      },
      {
        id: "entry-fuel-vapor-0922",
        itemId: "item-fuel-vapor",
        name: "油气回收真空度",
        device: "油气回收泵",
        required: true,
        frozen: { type: "number", unit: "kPa", min: -6, max: -2 },
        value: "-3.5",
        judgement: "normal",
        closure: { status: "open" },
      },
      {
        id: "entry-fuel-hose-0922",
        itemId: "item-fuel-hose",
        name: "加油枪软管外观",
        device: "2号加油机",
        required: true,
        frozen: { type: "select", options: ["完好", "破损"] },
        value: "完好",
        judgement: "normal",
        closure: { status: "open" },
      },
    ],
  },
  {
    id: "rec-tank-0922",
    area: "油罐区",
    inspector: "张倩",
    inspectedAt: "2026-09-22T10:10",
    submittedAt: "2026-09-22T02:20:00.000Z",
    templateId: "tpl-tank-v1",
    templateName: "油罐区安全巡检标准",
    templateVersion: 1,
    entries: [
      {
        id: "entry-tank-level-0922",
        itemId: "item-tank-level",
        name: "油罐液位",
        device: "2号柴油罐",
        required: true,
        frozen: { type: "number", unit: "mm", min: 800, max: 2400 },
        value: "1750",
        judgement: "normal",
        closure: { status: "open" },
      },
      {
        id: "entry-tank-gas-0922",
        itemId: "item-tank-gas",
        name: "可燃气浓度",
        device: "罐区气体报警器",
        required: true,
        frozen: { type: "number", unit: "%LEL", min: 0, max: 10 },
        value: "4",
        judgement: "normal",
        closure: { status: "open" },
      },
      {
        id: "entry-tank-seal-0922",
        itemId: "item-tank-seal",
        name: "卸油口密封",
        device: "卸油口",
        required: true,
        frozen: { type: "select", options: ["完好", "老化", "渗漏"] },
        value: "老化",
        judgement: "abnormal",
        closure: { status: "open" },
      },
    ],
  },
];

const seedTasks: ReviewTask[] = [
  {
    id: "task-seal-0922",
    recordId: "rec-tank-0922",
    entryId: "entry-tank-seal-0922",
    area: "油罐区",
    itemName: "卸油口密封",
    device: "卸油口",
    originalInspector: "张倩",
    originalValue: "老化",
    originalJudgement: "abnormal",
    spotInspector: "王主任",
    spotValue: "完好",
    spotJudgement: "normal",
    reason: "判定偏离：原记录「异常」，抽检判定「正常」",
    status: "pending",
    createdAt: "2026-09-22T06:00:00.000Z",
  },
];

export function seedState(): PersistedState {
  return {
    version: 2,
    templates: seedTemplates,
    records: seedRecords,
    tasks: seedTasks,
  };
}
